// GENERATED by tools/gen_hand_config.py from config/hand.json -- do not edit.
#pragma once

#define N_MOTORS 8
#define N_PRIMS 5
#define WATCHDOG_MS 1500
#define DUTY_LIMIT 200
#define RAMP_MS 80
#define PWM_FREQ_HZ 20000
#define PWM_BITS 8

struct Motor { uint8_t in1; uint8_t in2; bool invert; uint16_t close_ms; uint16_t open_ms; const char* role; };
static const Motor MOTORS[N_MOTORS] = {
  { 25, 26, false,  650,  780, "thumb_flex" },  // 0
  { 27, 14, false,  500,  600, "thumb_oppose" },  // 1
  { 12, 13, false,  600,  720, "index_flex" },  // 2
  { 33, 32, false,  600,  720, "middle_flex" },  // 3
  {  4, 16, false,  600,  720, "ring_flex" },  // 4
  { 17,  5, false,  580,  700, "pinky_flex" },  // 5
  { 18, 19, false,  500,  600, "aux0" },  // 6
  { 21, 22, false,  500,  600, "aux1" },  // 7
};

struct Prim { const char* name; int8_t dir[N_MOTORS]; };
static const Prim PRIMS[N_PRIMS] = {
  { "open", { -1, -1, -1, -1, -1, -1, -1, -1 } },
  { "power", {  1,  1,  1,  1,  1,  1,  0,  0 } },
  { "pinch", {  1,  1,  1, -1, -1, -1,  0,  0 } },
  { "point", {  1,  0, -1,  1,  1,  1,  0,  0 } },
  { "tripod", {  1,  1,  1,  1, -1, -1,  0,  0 } },
};

