"""Generate firmware/esp32_hand/config.h from config/hand.json.

Pin map, primitive table, and timings live in the JSON so the host and the
firmware cannot disagree about them. Run after editing config/hand.json:

    python tools/gen_hand_config.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "config" / "hand.json"
DST = ROOT / "firmware" / "esp32_hand" / "config.h"

cfg = json.loads(SRC.read_text())
motors = sorted(cfg["motors"], key=lambda m: m["id"])
roles = [m["role"] for m in motors]
prims = cfg["primitives"]

for name, table in prims.items():
    unknown = set(table) - set(roles)
    if unknown:
        raise SystemExit(f"primitive {name!r} references unknown roles: {sorted(unknown)}")

L = []
w = L.append
w("// GENERATED by tools/gen_hand_config.py from config/hand.json -- do not edit.")
w("#pragma once")
w("")
w(f"#define N_MOTORS {len(motors)}")
w(f"#define N_PRIMS {len(prims)}")
w(f"#define WATCHDOG_MS {cfg['watchdog_ms']}")
w(f"#define DUTY_LIMIT {cfg['duty_limit']}")
w(f"#define RAMP_MS {cfg['ramp_ms']}")
w(f"#define PWM_FREQ_HZ {cfg['pwm_freq_hz']}")
w(f"#define PWM_BITS {cfg['pwm_bits']}")
w("")
w("struct Motor { uint8_t in1; uint8_t in2; bool invert; uint16_t close_ms; uint16_t open_ms; const char* role; };")
w("static const Motor MOTORS[N_MOTORS] = {")
for m in motors:
    w(f"  {{ {m['in1']:2d}, {m['in2']:2d}, {str(m['invert']).lower():5s}, "
      f"{m['close_ms']:4d}, {m['open_ms']:4d}, \"{m['role']}\" }},  // {m['id']}")
w("};")
w("")
w("struct Prim { const char* name; int8_t dir[N_MOTORS]; };")
w("static const Prim PRIMS[N_PRIMS] = {")
for name, table in prims.items():
    dirs = ", ".join(f"{int(table.get(r, 0)):2d}" for r in roles)
    w(f'  {{ "{name}", {{ {dirs} }} }},')
w("};")
w("")

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text("\n".join(L) + "\n")
print(f"wrote {DST.relative_to(ROOT)}: {len(motors)} motors, {len(prims)} primitives")
